In [5]:
import ntpath
import os
import numpy as np
import pandas as pd

In [6]:
def csv_to_pyarray(csv_in, file_out=None, array_name=None, enquote_elements=True, header=None, wrap=50):
    csv_filename, csv_file_extension = os.path.splitext(csv_in)
    csv_basename = ntpath.basename(csv_in).replace(csv_file_extension, '')
    file_out = file_out or csv_in.replace(csv_file_extension, '.py')
    array_name = array_name or csv_basename


    data = np.array(pd.read_csv(csv_in, header=header)).ravel()
    pyarray = '{0} = ['.format(array_name)
    length = 0
    for i, x in enumerate(data):
        length += len(str(x))
        if length > wrap:
            pyarray = "{0}{1}".format(pyarray, '\n')
            length = 0
        pyarray = "{0}'{1}', ".format(pyarray, x) if enquote_elements else "{0}{1}, ".format(pyarray, x)


    pyarray = '{0}]'.format(pyarray.rstrip()[:-1])
    with open(file_out, "w") as text_file:
        text_file.write("{0}".format(pyarray))

In [7]:
!touch test.csv

In [18]:
os.path.splitext('test.csv')

('test', '.csv')

In [10]:
csv_to_pyarray('test.csv')

In [ ]:
# %load test.py
test = ['1', '2', '3', '4', '5', '11', '22', '31', '112', '141', '131', '232', '11', '323', '12']

In [19]:
import numpy as np

In [23]:
a = np.array([1,3])
b = np.array([2,3])
np.row_stack((a,b))

array([[1, 3],
       [2, 3]])

In [27]:
np.hstack((a,b))

array([1, 3, 2, 3])

In [28]:
np.vstack((a,b))

array([[1, 3],
       [2, 3]])